import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./Hero Components/navbar";
import Footer from "./Hero Components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="flex flex-col min-h-screen justify-between pt-60">
        <div className="flex-grow">
          <NavBar />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
